import type { Metadata } from "next";
import "@/styles/globals.css";
import { MuteButton } from "@/components/mute-button";
import { fuzzyBubbles, pangolin } from "@/configs/font";
import { AudioPreloaderProvider } from "@/providers/audio-preloader-provider";
import { ModalContentWrapper, ModalProvider } from "@/providers/modal-provider";
import QueryProvider from "@/providers/query-provider";
import { QuestProvider } from "@/providers/quest-provider";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
	modal,
}: {
	children: React.ReactNode;
	modal: React.ReactNode;
}) {
	return (
		<html lang="en" className={`${fuzzyBubbles.variable} ${pangolin.variable}`}>
			<body className={`antialiased bg-purple-400 overflow-hidden`}>
				<QueryProvider>
					<QuestProvider>
						<AudioPreloaderProvider>
							<ModalProvider>
								<ModalContentWrapper>
									<MuteButton className="fixed bottom-4 left-4 z-50" />
									{children}
								</ModalContentWrapper>
								{modal}
							</ModalProvider>
						</AudioPreloaderProvider>
					</QuestProvider>
				</QueryProvider>
			</body>
		</html>
	);
}
