import type { Metadata } from "next";
import "@/styles/globals.css";
import { AudioPreloader } from "@/components/audio-preloader";
import { fuzzyBubbles, googleSans, pangolin } from "@/configs/font";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={`${fuzzyBubbles.variable} ${pangolin.variable} ${googleSans.variable}`}
		>
			<body className={`antialiased doodle`}>
				<AudioPreloader />
				{children}
			</body>
		</html>
	);
}
